export default {
	lang:
	{
		
		/**************************** 【常用词】 **************************************/
		'恒勃智驾':['恒勃智驾','HB Link'],
		'确认':['确认','Ok'],
		'确定':['确定','Ok'],
		'取消':['取消','Cancel'],
		'提示':['提示','Tips'],
		'删除':['删除','Delete'],
		'确定删除':['确定删除','Confirm Delete'],
		'重置':['重置','Reset'],
		'全部':['全部','All'],
		'上传':['上传','Upload'],
		'下载':['下载','Download'],
		'连接中...':['连接中...','Connecting...'],
		'WIFI已连接':['WIFI已连接','Successful'],
		'加载中':['加载中...','Loading'],
		'展开':['展开','Open'],
		'无网络,暂无云端视频':['无网络,暂无云端视频','No Network, Currently No Cloud Video Available'],
		'清理完成':['清理完成','Cleaning Completed'],
		'删除失败！':['删除失败！','Delete Failed!'],
		'分':['分','m'],
		'秒':['秒','s'],
		'搜索':['搜索','Search'],
		'视频时长':['视频时长','Duration'],
		'视频大小':['视频大小','Size'],
		'视频时间':['视频时间','Time'],
		'点':['点','Hour'],
		'当前视频':['当前视频','Current'],
		'保存到相册':['保存到相册','Save To Album'],
		'视频列表':['视频列表','Video List'],
		'关闭':['关闭','Close'],
		'恭喜您，视频下载到本地完成，您可以到【在路上】的【本地】列表进行查看，是否返回DVR列表页面？':['恭喜您，视频下载到本地完成，您可以到【在路上】的【本地】列表进行查看，是否返回DVR列表页面？','Congratulations, the video download has been completed locally. You can go to the [Local] list in [On the Road] to view it. Do you want to return to the DVR list page?'],
		'保存失败':['保存失败','Save Failed'],
		'获取文件失败':['获取文件失败','Failed To Retrieve File'],
		'上传登陆失败':['上传登陆失败','Upload Login 	Failed'],
		'抱歉，网络连接失败,无法上传云端！':['抱歉，网络连接失败,无法上传云端！','Sorry, Network Connection Failed'],
		'提示：密码已复制，可直接粘贴密码':['提示：密码已复制，可直接粘贴密码','Tip: Password Has Been Copied, You Can Directly Paste The Password'],
		'您当前连接的WIFI不正确，请切换为设备WIFI':['您当前连接的WIFI不正确，请切换为设备WIFI','The WIFI You Are Currently Connected To Is Incorrect. Please Switch To Device WIFI'],
		'返回':['返回','Back'],
		'案例中心':['案例中心','Case Center'],
		'案例':['案例','Case'],
		'一般工业/通讯设备和元器件':['一般工业/通讯设备和元器件','General Industrial/Communication Equipment And Components'],
		'视频':['视频','Video'],
		'精华':['精华','Essence'],
		'置顶':['置顶','Top'],
		'设备连接失败，请检查是否已打开设备OTA升级界面':['设备连接失败，请检查是否已打开设备OTA升级界面','Device Connection Failed, Please Check If The Device OTA Upgrade Interface Has Been Ppened'],
		'WIFI已连接':['WIFI已连接!','Connected!'],
		'请求中':['请求中...','Requesting'],
		'获取文件失败,请重启应用':['获取文件失败,请重启应用','Failed To Retrieve File, Please Restart The Application'],
		'读取文件成功':['读取文件成功','Successfully Read File'],
		'正在保存信息':['正在保存信息','Saving Information'],
		'路径':['路径','path'],
		'修改信息失败,请重新操作':['修改信息失败,请重新操作','Failed To Modify Information, Please Try Again'],
		'保存文件失败,请重新操作':['保存文件失败,请重新操作','Saving File Failed, Please Try Again'],
		'请求系统失败,请重新操作':['请求系统失败,请重新操作','Request System Failed, Please Try Again'],
		'获取目标目录失败':['获取目标目录失败:','Failed To Obtain Target Directory:'],
		'获取目录失败':['获取目录失败:','Failed To Retrieve Directory:'],
		'目录创建失败':['目录创建失败:','Directory Creation Failed:'],
		'错误':['错误','error'],
		'复制时出现错误':['复制时出现错误','An Error Occurred While Copying'],
		'错误：路径必须是文件':['错误：路径必须是文件','Error: Path Must Be A File'],
		'路径必须是文件':['路径必须是文件','The Path Must Be A File'],
		'打开文件系统时出错':['打开文件系统时出错','Error Opening File System'],
		'正在下载保存到相册':['正在下载保存到相册','Downloading And Saving To Album'],
		'已保存相册':['已保存相册!','Album saved'],
		'已保存相册失败，检查是否权限已打开':['已保存相册失败，检查是否权限已打开?','Failed To Save Album, Check If Permissions Have Been Opened'],
		'视频下载失败，状态码':['视频下载失败，状态码','Video Download Failed With Status Code'],
		'下载视频失败':['下载视频失败','Download Video Failed'],
		'当前视频已保存在本地，是否需要重新下载':['当前视频已保存在本地，是否需要重新下载?','The Current Video Has Been Saved Locally. Do You Need To Download It Again'],
		'当前已连接设备':['当前已连接设备','Currently connected device'],
		'无本地视频，可到DVR下载':['无本地视频，可到DVR下载','No Local Videos Available, Can Be Downloaded From DVR'],
		
		/**************************** 【首页】 **************************************/
		'导航寻车': ['寻车导航', 'Navigation To Find Car'],
		'设备信息': ['设备详情', 'Device Information'],
		'设备': ['设备', 'Device'],
		'系统': ['系统', 'System'],
		'车辆信息': ['车辆信息', 'Vehicle Information'],
		'仪表设置': ['仪表配置', 'Instrument Cluster Settings'],
		'扫一扫': ['扫描', 'Scan'],
		'未连接': ['未连接', 'Not Connected'],
		'仪表版本非最新，请检查': ['仪表非最新版本，请查', 'Check仪表 Version Not Latest'],
		'连接中': ['连接中', 'Connecting'],
		'连接失败': ['连失败', 'Failed'],
		'已连接': ['已连接', 'Connected'],
		'您当前还未绑定任何设备哦': ['您当前还未绑定任何设备哦', 'You Havent Tied Your Device Yet'],
		'立即扫码绑定': ['立即扫码绑定', 'Scanning'],
		'加载云端视频':['加载云端视频','Load Cloud Video'],
		'已上传云端':['已上传云端','Uploaded To Cloud'],
		'本地已下载':['本地已下载','Local Download'],
		'恭喜您，当前视频已上传到云端，在云端列表可查看！':['恭喜您，当前视频已上传到云端，在云端列表可查看！','Congratulations, The Current Video Has Been Uploaded To The Cloud And Can Be Viewed In The Cloud List!'],
		'抱歉，当前连接的是设备WIFI，无法加载云端视频，是否需要断开设备网络加载云端视频？':['抱歉，当前连接的是设备WIFI，无法加载云端视频，是否需要断开设备网络加载云端视频？','Sorry, Currently Connected To Device WIFI, Unable To Load Cloud Video. Do You Need To Disconnect The Device Network To Load Cloud Video?'],
		
		
		
		
		
		/**************************** 【设备列表】 **************************************/
		'当前设备': ['当前设备', 'Current Device'],
		'切换设备': ['切换设备', 'Switching Equipment'],
		'确认要解绑该设备吗': ['确认要解绑该设备吗？', 'Are You Sure You Want To Unstrap The Device？'],
		'确认要切换到该设备吗': ['确认要切换到该设备吗？', 'Are You Sure You Want To Switch To This Device？'],
		'全部设备':['全部设备','All Devices'],
		'全部':['全部','All'],
		'前置':['前置','Front'],
		'后置':['后置','End'],
		'前录': ['前录', 'Front'],
		'后录': ['后录', 'End'],
		'选择日期':['选择日期','Select Date'],
		'断开设备':['断开设备...','Disconnect Device'],
		'设备已被其他用户绑定，不支持重复绑定设备！':['设备已被其他用户绑定，不支持重复绑定设备！','The Device Has Been Bound By Another User'],
		'恭喜您，设备绑定成功，当前设备的设备号为':['恭喜您，设备绑定成功，当前设备的设备号为','Congratulations, The Device Has Been Successfully Bound. The Current Device Number Is'],
		'注意：设备WIFI名称跟设备号是同一个':['注意：设备WIFI名称跟设备号是同一个','Note: The Device WIFI Name Dnd Device Number Are The Same'],
		'抱歉，获取定位信息授权失败！如果wifi无法识别或者设备连接失败，请到手机设置【打开定位授权】':['抱歉，获取定位信息授权失败！如果wifi无法识别或者设备连接失败，请到手机设置【打开定位授权】','Sorry, Obtaining Location Information Authorization Failed! If The WiFi Cannot Recognize Or The Device Connection Fails, Please Go To The Phone Settings [Open Location Authorization]'],
		'已是当前设备，无需切换！':['已是当前设备，无需切换！','It Is Already The Current Device, No Need To Switch!'],
		
		/**************************** 【设备仪表信息详情页面】 **************************************/
		'当前设备': ['当前设备', 'Current Device'],
		'剩余电量': ['剩余电量', 'Remaining Battery'],
		'主题': ['主题', 'Theme'],
		'背光': ['背光', 'Backlight'],
		'语言': ['语言', 'Language'],
		'单位': ['单位', 'Unit'],
		'自动': ['自动', 'Automatic'],
		'白天': ['白天', 'Daytime'],
		'黑夜': ['黑夜', 'Nighttime'],
		'自动调整': ['自动', 'Auto-adjust'],
		'公里': ['公里', 'Kilometers'],
		'英里': ['英里', 'Miles'],
		/**************************** 【dvr列表页面】 **************************************/
		'筛选内容': ['筛选内容', 'Filter Content'],
		'设备筛选': ['设备筛选', 'Device Filter'],
		'录制方向': ['录制方向', 'Direction'],
		'请选择时间段': ['请选择时间段', 'Please Select A Time Period'],
		'视频名称': ['视频名称', 'Video Name'],
		'确认要删除当前视频吗': ['确认要删除当前视频吗？', 'Are You Sure You Want To Delete The Current Video?'],
		'删除成功': ['删除成功！', 'Deleted Successfully!'],

		'是否确认一键删除设备所有视频，一旦删除将无法恢复哦':['是否确认一键删除设备所有视频，一旦删除将无法恢复哦','Do You Confirm To Delete All The Videos Of The Device With One Click? Once Deleted, It Will Not Be Restored?'],
		'请选择要删除的视频文件':['请选择要删除的视频文件','Please select the video file you want to delete.'],
		'是否确认把选中的视频批量删除，一旦删除将无法恢复哦':['是否确认把选中的视频批量删除，一旦删除将无法恢复哦？','Do You Confirm To Delete The Selected Videos In Batches? Once Deleted, It Will Not Be Restored?'],
		'是否确认':['是否确认','Confirm or not'],
		'视频全部删除，一旦删除将无法恢复哦':['视频全部删除，一旦删除将无法恢复哦','All Videos Deleted, Once Deleted Will Not Be Able To Recover Oh?'],
		'请选择视频':['请选择视频！','Please select Video!'],
		'您可以点击查看视频，或长按更多操作~':['您可以点击查看视频，或长按更多操作~','You Can Click To View The Video, Or Long Press For More Actions~'],
		'点击连接设备':['点击连接设备','Connect Device'],
		'未连接设备':['未连接设备','Unconnected Device'],
		'设备连接步骤':['设备连接步骤','Device Connection Steps'],
		'如果您是首次连接或自动连接失败，请根据以下步骤操作！':['如果您是首次连接或自动连接失败，请根据以下步骤操作！','If You Are Connecting For The First Time Or If Automatic Connection Fails, Please Follow The Steps Below!'],
		'第一步、打开仪表设备，将设备调节到以下苹果手机投屏界面':['第一步、打开仪表设备，将设备调节到以下苹果手机投屏界面','Step 1: Open The Instrument Panel And Adjust The Device To The Following Apple Phone Screen Projection Interface'],
		'第二步、进入手机WIFI列表界面，找到：':['第二步、进入手机WIFI列表界面，找到：','Step 2, Enter The Mobile WIFI List Interface And Find:'],
		'更多':['更多','More'],
		'至':['至','To'],
		'年':['年','Y'],
		'月':['月','M'],
		'下载当前视频':['下载当前视频','Download current video'],
		'删除此视频':['删除此视频','Delete current video'],
		'批量删除视频':['批量删除视频','Batch delete videos'],
		'删除所有DVR视频':['删除所有DVR视频','Delete all video'],
		'删除选中':['删除选中','Delete check'],
		'删除当日':['删除当日','Delete today'],
		
		
		/**************************** 【在路上页面】 **************************************/
		'云端': ['云端', 'Cloud'],
		'本地': ['本地', 'Local'],
		'无数据': ['无数据', 'No Data'],
		'录制日期': ['录制日期', 'Recording Date'],
		
		'正在下载': ['正在下载', 'Downloading'],
		'下载完成': ['下载完成！', 'Download Complete!'],
		'正在上传': ['正在上传', 'Uploading'],
		'上传完成': ['上传完成', 'Upload Complete'],
		'上传服务错误，请稍后重试': ['上传服务错误，请稍后重试!', 'Upload Service Error, Please Try Again Later!'],
		'一键清空缓存':['一键清空缓存','Clear all cache'],

		/**************************** 【OTA升级页面】 **************************************/
		'当前设备信息': ['当前设备信息', 'Device Information'],
	  '当前版本': ['当前版本', 'Current Version'],
	  '最新版本': ['最新版本', 'Latest Version'],
	  '最新版本描述': ['最新版本描述', 'Latest Version Description'],
	  '已是最新版本': ['已是最新版本', 'Already The Latest Version'],
	  'OTA升级包': ['OTA升级包', 'OTA Upgrade Package'],
	  '发现新版本': ['发现新版本!', 'New Version Found!'],
	  'OTA固件升级,确认车机是否进入OTA升级界面': ['OTA固件升级,确认车机是否进入OTA升级界面？', 'OTA Firmware Upgrade, Confirm If The Device Has Entered The OTA Update Interface?'],
	  '正在下载所需升级包': ['正在下载所需升级包', 'Downloading Required Update Package'],
	  '开始检查升级包': ['开始检查升级包', 'Starting To Check The Update Package'],
	  
	  '升级包检查成功, 请求连接车机中': ['升级包检查成功, 请求连接车机中', 'Upgrade Package Checked Successfully, Requesting Connection To The Device'],
	  '车机连接成功，开始传输升级包': ['车机连接成功，开始传输升级包', 'Device Connected Successfully, Starting To Transfer Upgrade Package'],
	  'wifi连接失败，请使用手动连接': ['wifi连接失败，请使用手动连接！', 'WiFi Connection Failed, Please Manually Connect!'],
	  '读取文件失败': ['读取文件失败！', 'File Read Failed!'],
	  '车机已是最新版本, 请重新扫描车机二维码更新信息': ['车机已是最新版本, 请重新扫描车机二维码更新信息', 'The Device Is Already Up-To-Date, Please Rescan The QR Code To Update Information'],
	  '正在传输升级包': ['正在传输升级包', 'Transferring Upgrade Package'],
	  
	  '升级包传输完成，等待设备升级': ['升级包传输完成，等待设备升级', 'Upgrade Package Transfer Complete, Awaiting Device Upgrade'],
	  '恭喜您，升级包传输完成，等待设备自动升级。设备会自动重启，重启成功即升级成功,是否需要切换到正常网络': ['恭喜您，升级包传输完成，等待设备自动升级。设备会自动重启，重启成功即升级成功,是否需要切换到正常网络', 'Congratulations, the Upgrade Package Transfer is Complete. Awaiting Automatic Device Upgrade. The Device Will Restart Automatically; Success Upon Restart. Switch to Normal Network?'],
	  '当前连接的网络是车机设备局域网络，是否切换': ['当前连接的网络是车机设备局域网络，是否切换', 'The Currently Connected Network Is The Devices Local Network. Would You Like To Switch?'],
	  'WIFI切换中...': ['WIFI切换中...', 'Switching WiFi...'],
	  'WIFI切换失败！请手动点击连接车机WIFI，然后确认继续升级': ['WIFI切换失败！请手动点击连接车机WIFI，然后确认继续升级', 'WiFi Switch Failed! Please Manually Connect To The Devices WiFi And Confirm To Continue Updating.'],
	  '网络切换成功，正在连接车机服务': ['网络切换成功，正在连接车机服务!', 'Network Switch Successful, Connecting to Device Services!'],
	  '进行手动连接。连接成功以后回到当前页面，点击下一步。如下图':['进行手动连接。连接成功以后回到当前页面，点击下一步。如下图','Make A Manual Connection. After Successfully Connecting, Return To The Current Page And Click Next. As Shown In The Following Figure'],
	  '下一步':['下一步','Next'],
	  '刷新':['刷新','Refresh'],
	  '清空':['清空','empty'],
	  '与设备服务连接时失败，检查是否将设备调节到以下苹果手机投屏界面':['与设备服务连接时失败，检查是否将设备调节到以下苹果手机投屏界面','Failed To Connect To Device Service. Check If The Device Has Been Adjusted To The Following Apple Phone Screen Mirroring Interface'],
	  
		

		/**************************** 【登录、注册】 **************************************/
		'您好':['您好','Hello!'],
		'欢迎使用':['欢迎使用','Welcome To'],
		'账号':['账号','Account'],
		'请输入账号':['请输入账号','Please Enter Your Account'],
		'密码':['密码','Password'],
		'请输入密码':['请输入密码','Please Enter Your Password'],
		'记住账号和密码':['记住账号和密码','Remember Account And Password'],
		'登 录':['登 录','Log In'],
		'还没有账号？点击注册':['还没有账号？点击注册','No Account Yet? Click To Register'],
		'请输入您的账号':['请输入您的账号','Please Enter Your Account'],
		'请输入您的密码':['请输入您的密码','Please Enter Your Password'],
		'登录成功':['登录成功！','Login OK!'],
		'账号密码错误':['账号密码错误！','Incorrect Account Or Password!'],
		'账号密码错误': ['账号密码错误！', 'Incorrect Account Or Password!'],
		'请输入手机号': ['请输入手机号！', 'Please Enter Your Phone Number.'],
		'请输入姓名': ['请输入姓名！', 'Please Enter Your Name.'],
		'请输入邮箱': ['请输入邮箱！', 'Please Enter Your Email.'],
		'请输入密码': ['请输入密码！', 'Please Enter Your Password.'],
		'确认密码': ['确认密码', 'Confirm Password'],
		'请输入确认密码': ['请输入确认密码！', 'Please Confirm Your Password.'],
		'注 册': ['注 册', 'Register'],
		'已有帐号？点击登录': ['已有帐号？点击登录', 'Already Have An Account? Click To Log In.'],
		'注册成功': ['注册成功！', 'Registration Successful!'],
		'网络连接中':['网络连接中','In Network Connection'],
		'网络异常，请重新尝试点击登录！':['网络异常，请重新尝试点击登录！','Network Abnormality, Please Try Clicking Login Again!'],
		'手机号格式不正确':['手机号格式不正确!','The Phone Number Format Is Incorrect'],
		'邮箱号格式不正确':['邮箱号格式不正确!','The Email Number Format Is Incorrect'],
		'您当前连接的是设备WIFI，暂无网络，无法操作用户信息！':['您当前连接的是设备WIFI，暂无网络，无法操作用户信息！','You Are Currently Connected To Device WIFI And Currently Have No Network, Unable To Access User Information!'],
		'开启':['开启','Open'],
		'打开连接':['打开连接','Open A Connection'],
		'关闭连接':['关闭连接','Close A Connection'],
		'发送消息':['发送消息','Send A Message'],
		'清空日志':['清空日志','Clear Logs'],
		'WebSocket连接中':['WebSocket连接中...！','WebSocket Connection In Progress!'],
		'报错':['报错！','report errors'],
		'WebSocket连接已打开':['WebSocket连接已打开!','WebSocket Connection Opened'],
		'收到服务器内容':['收到服务器内容：','Received Server Content'],
		'WebSocket连接打开失败，请检查':['WebSocket连接打开失败，请检查!','WebSocket Connection Failed To Open, Please Check'],
		'发送数据成功':['发送数据成功','Successfully Sent Data'],
		'发送数据失败':['发送数据失败','Sending Data Failed'],
		'设备连接断开':['设备连接断开!','Device Connection Disconnected'],
		'验证失败，请重新登录':['验证失败，请重新登录','Verification Failed, Please Log In Again'],
		
		/**************************** 【设置界面】 **************************************/
		'必须wifi环境上传':['必须wifi环境上传','Must Be Uploaded In Wifi Environment'],
		'上传成功提示窗':['上传成功提示窗','Upload Success Prompt'],
		'下载成功提示窗':['下载成功提示窗','Download Success Prompt'],
		'地区':['地区','Area'],
		'语言':['语言','Language'],
		'关于我们':['关于我们','About Us'],
		
		
		'语言切换成功':['语言切换成功！','Language Switch Successful！'],
		'修改提示成功':['修改提示成功！','Modify The Prompt Successfull！'],
		'修改地区成功':['修改地区成功！','Modified Region Succeeded！'],
		
		'中国':['中国','China'],
		'美国':['美国','America'],
		
		'中文':['中文','中文'],
		'英文':['English','English'],
		
		'当前版本':['当前版本','Current Version'],
		'新版本':['新版本','New Edition'],
		'当前已是最新版本':['当前已是最新版本','This Is The Latest Version'],
		
		/**************************** 【页面导航标题】 **************************************/
		'用户信息':['用户信息','User Information'],
		'上传头像':['上传头像','Upload Profile Picture'],
		'用户反馈':['用户反馈','User Feedback'],
		'设置':['设置','Settings'],
		'隐私协议':['隐私协议','Privacy Agreement'],
		'关于':['关于','About Us'],
		'登录':['登录','Log In'],
		'注册':['注册','Sign In'],
		'视频详情':['视频详情','Video Details'],
		'设备列表':['设备列表','Device List'],
		'在路上':['在路上','On Road'],
		'我的':['我的','My'],
		
		/**************************** 【用户反馈、关于、头像等页面】 **************************************/
		'设置信息':['设置信息','Set Information'],
		'退出登录':['退出登录','Log Out'],
		'确认要退出登录吗':['确认要退出登录吗？','Are You Sure You Want To Log Out？'],
		'请在此处输入反馈信息':['请在此处输入反馈信息','Please Enter Your Feedback Here'],
		'提交反馈':['提交反馈','Submit feedback'],
		'提交用户反馈成功':['提交用户反馈成功!','Submitting User Feedback Succeeded！'],
		'重新选择':['重新选择!','Reselect'],
		'上传成功':['上传成功!','Successfully!'],
		'上传失败':['上传失败!','Fail!'],
		'上传中':['上传中','Uploading...'],
		
		/**************************** 【用户信息】 **************************************/
		'头像':['头像','Avatar'],
		'姓名':['姓名','Name'],
		'手机号':['手机号','Phone'],
		'邮箱':['邮箱','Email'],
		'密码':['密码','Password'],
		'新邮箱':['新邮箱','Email'],
		'新号码':['新号码','Phone'],
		'请输入新姓名':['请输入新姓名','Enter New Name'],
		'请输入新号码':['请输入新号码','Enter New Phone Number'],
		'请输入新邮箱':['请输入新邮箱','Enter New Email'],
		'请输入原密码':['请输入原密码','Enter Original Password'],
		'请输入新密码':['请输入新密码','Enter New Password'],
		'请输入确认新密码':['请输入确认新密码','Confirm New Password'],
		'原密码':['原密码','Original'],
		'新密码':['新密码','New'],
		'确认新密码':['确认新密码','Confirm'],
		'修改姓名成功':['修改姓名成功！','Name Updated Successfully!'],
		'修改手机号成功':['修改手机号成功！','Phone Number Updated Successfully!'],
		'修改邮箱成功':['修改邮箱成功！','Email Updated Successfully!'],
		'两次密码输入不一致':['两次密码输入不一致！','Passwords Do Not Match!'],
		'修改密码成功':['修改密码成功！','Password Updated Successfully!'],
		'此处显示隐私说明文本':['此处显示隐私说明文本！','The Text Of The Privacy Note Is Displayed Here!'],
		
		/**************************** 【后台接口返回错误对照表】 **************************************/
		'90001':['用户不存在','The User Does Not Exist'],
		'90002':['用户已经被冻结','The User Has Been Frozen'],
		'90003':['用户密码不正确','The User Password Is Incorrect'],
		'90004':['用户旧密码不正确','The Old Password Ss Incorrect'],
		'90005':['请求中不存在角色凭证','No Role Credentials Exist In The Request'],
		'90006':['请求中不存在用户凭证','No User Credentials Exist In The Request'],
		'90007':['系统无此用户权限缓存','The System Does Not Have This User Permission Cache'],
		'90008':['系统无此用户权限缓存','No User Permission Cache The System Does Not Have The User Permission Cache'],
		'90009':['字典值校验失败','Dictionary Value Verification Failed'],
		'90010':['超级管理员不允许被删除','The Super Administrator Cannot Be Deleted'],
		'90011':['系统角色不允许被删除','The System Role Cannot Be Deleted'],
		'90012':['不存在的角色','Role Does Not Exist'],
		'90013':['角色存在用户关系，不允许被删除','The Role Has User Relationships And Cannot Be Deleted'],
		'90014':['appId校验失败','The AppId Verification Fails'],
		'90015':['appId已被冻结','The AppId Is Frozen'],
		'90016':['密钥不正确','Incorrect Key'],
		'90017':['CAS授权失败','The CAS Authorization Fails'],
		'90018':['无效的票据','Invalid Bill'],
		'90019':['解析错误','Parse Error'],
		'90030':['系统角色不允许被修改','The System Role Cannot Be Modified'],
		'90031':['不允许系统角色添加','The System Role Cannot Be Added'],
		'90032':['手机号码已注册','The Mobile Number Is Registered'],
		'90033':['邮箱已注册','Email Registered'],
		'90034':['用户添加失败','User Addition Failure'],
		'90035':['服务器无负载信息','The Server Has No Load Information'],
		'90036':['用户绑定了设备信息','The User Is Bound With Device Information'],
		'90037':['云服务器调用失败','Cloud Server Invocation Failed'],
		'90038':['请求未携带视频数据','The Request Does Not Carry Video Data'],
		'90039':['摄像头类型错误', 'Camera Type Error'],
		'90040':['设备不存在','Device Does Not Exist'],
		'90041':['视频文件已上传，不需要重复上传','The Video File Has Been Uploaded. You Do Not Need To Upload It Again'],
		
		
		'50001':['参数不正确','Incorrect Parameter'],
		'50002':['数据不存在','Data Does Not Exist'],
		'50003':['上传文件格式不正确','The Uploaded File Format Is Incorrect'],
		'50004':['上传文件大小不正确','The Uploaded File Size Is Incorrect'],
		'50005':['删除视频设备序列号不可为空','Delete Video Device Serial Number Cannot Be Empty'],
		'50006':['删除视频的视频资源不存在','Delete A Video Device Serial Number Cannot Ee Empty. The Video Resource For Deleting A Video Does Not Exist'],
		'50007':['不存在的设备','The Device Does Not Exist'],
		'50008':['不存在的视频资源','The video Resource Does Not Exist'],
		'50009':['不存在的OSAPP项目编号','The OSAPP Project Number Eoes Not Exist'],
		'50010':['不存在的MCU项目编号','The MCU Project Number Does Not Exist'],
		'50011':['不存在的OSAPP固件版本','The OSAPP Firmware Version Does Not Exist'],
		'50012':['不存在的MCU固件版本','The MCU Firmware Version Does Not Exist'],
		'50014':['设备不存在车辆信息','The Device Does Not Have Vehicle Information'],
		'50015':['设备不存在配置信息','No Configuration Information Exists On The Device'],
		'50016':['终端用户无操作权限','The Terminal User Has No Operation Permission'],
		'50017':['不存在的文件服务','The File Service Does Not Exist'],
		'50018':['文件服务编号已存在','The File Service Number Already Exists'],
		'50019':['文件服务已经被视频数据引用，删除失败','The File Service Has Been Referenced By Video Data And Failed To Be Deleted'],
		'50020':['设备已经被视频数据引用，删除失败','The Device Is Referenced By Video Data And Fails To Be Deleted'],
		'50021':['项目已经被设备数据引用，删除失败','The Item Has Been Referenced By Device Data And Failed To Be Deleted'],
		'50022':['项目已经被OSAPP固件包数据引用，删除失败','The Item Has Been Referenced By The OSAPP Firmware Package And Failed To Be Deleted'],
		'50023':['MCU项目已经被设备数据引用，删除失败','The MCU Item Has Been Referenced By The Device Data And Failed To Be Deleted'],
		'50024':['MCU项目已经被OSAPP固件包数据引用，删除失败','The MCU Project Has Been Referenced By OSAPP Firmware Package Data And Failed To Be Deleted'],
		'50025':['APP软件已被APP升级包数据引用，删除失败','The APP Software Has Been Referenced By The APP Upgrade Package And Failed To Be Deleted'],
		'50026':['APP软件不存在','The APP Soft Does Not Exist']
	}

	,getLangContent:function(str,langIndex){
		if(!langIndex||langIndex==undefined){
			var index=uni.getStorageSync('language');
			if(index){
				langIndex=Number(index);
			}else{
				langIndex=0;
			}
		}
		if(this.$lang&&this.$lang[str]){
			try{
				return this.$lang[str][langIndex];
			}catch(e){
				console.log('未找到：',str)
				return str;
			}
		}else{
			return str;
		}
	},
}
